// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: v1/rpc/parquet.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *OpenFileReq) Reset() {
	*x = OpenFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rpc_parquet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileReq) ProtoMessage() {}

func (x *OpenFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rpc_parquet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileReq.ProtoReflect.Descriptor instead.
func (*OpenFileReq) Descriptor() ([]byte, []int) {
	return file_v1_rpc_parquet_proto_rawDescGZIP(), []int{0}
}

func (x *OpenFileReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FileInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename  string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	NumOfRows int64  `protobuf:"varint,2,opt,name=numOfRows,proto3" json:"numOfRows,omitempty"`
}

func (x *FileInfoResp) Reset() {
	*x = FileInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rpc_parquet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoResp) ProtoMessage() {}

func (x *FileInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rpc_parquet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoResp.ProtoReflect.Descriptor instead.
func (*FileInfoResp) Descriptor() ([]byte, []int) {
	return file_v1_rpc_parquet_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfoResp) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInfoResp) GetNumOfRows() int64 {
	if x != nil {
		return x.NumOfRows
	}
	return 0
}

type GetRowsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	StartLine int32  `protobuf:"varint,2,opt,name=startLine,proto3" json:"startLine,omitempty"`
	Offset    int32  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetRowsReq) Reset() {
	*x = GetRowsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rpc_parquet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRowsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRowsReq) ProtoMessage() {}

func (x *GetRowsReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rpc_parquet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRowsReq.ProtoReflect.Descriptor instead.
func (*GetRowsReq) Descriptor() ([]byte, []int) {
	return file_v1_rpc_parquet_proto_rawDescGZIP(), []int{2}
}

func (x *GetRowsReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetRowsReq) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *GetRowsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []byte `protobuf:"bytes,1,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rpc_parquet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rpc_parquet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_v1_rpc_parquet_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetFields() []byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_v1_rpc_parquet_proto protoreflect.FileDescriptor

var file_v1_rpc_parquet_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x31, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x29, 0x0a, 0x0b, 0x4f,
	0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x52, 0x6f, 0x77, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x52, 0x6f, 0x77, 0x73,
	0x22, 0x56, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x1d, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x32, 0x67, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x71, 0x75,
	0x65, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x52, 0x6f, 0x77,
	0x73, 0x12, 0x0f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x77, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x6f, 0x77, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6f, 0x66, 0x66, 0x65, 0x65, 0x61, 0x6e, 0x64, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x64, 0x6f,
	0x75, 0x67, 0x6c, 0x61, 0x73, 0x69, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_rpc_parquet_proto_rawDescOnce sync.Once
	file_v1_rpc_parquet_proto_rawDescData = file_v1_rpc_parquet_proto_rawDesc
)

func file_v1_rpc_parquet_proto_rawDescGZIP() []byte {
	file_v1_rpc_parquet_proto_rawDescOnce.Do(func() {
		file_v1_rpc_parquet_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_rpc_parquet_proto_rawDescData)
	})
	return file_v1_rpc_parquet_proto_rawDescData
}

var file_v1_rpc_parquet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_rpc_parquet_proto_goTypes = []interface{}{
	(*OpenFileReq)(nil),  // 0: rpc.OpenFileReq
	(*FileInfoResp)(nil), // 1: rpc.FileInfoResp
	(*GetRowsReq)(nil),   // 2: rpc.GetRowsReq
	(*Row)(nil),          // 3: rpc.Row
}
var file_v1_rpc_parquet_proto_depIdxs = []int32{
	0, // 0: rpc.Parquet.OpenFile:input_type -> rpc.OpenFileReq
	2, // 1: rpc.Parquet.ReadRows:input_type -> rpc.GetRowsReq
	1, // 2: rpc.Parquet.OpenFile:output_type -> rpc.FileInfoResp
	3, // 3: rpc.Parquet.ReadRows:output_type -> rpc.Row
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_rpc_parquet_proto_init() }
func file_v1_rpc_parquet_proto_init() {
	if File_v1_rpc_parquet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_rpc_parquet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_rpc_parquet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_rpc_parquet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRowsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_rpc_parquet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_rpc_parquet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_rpc_parquet_proto_goTypes,
		DependencyIndexes: file_v1_rpc_parquet_proto_depIdxs,
		MessageInfos:      file_v1_rpc_parquet_proto_msgTypes,
	}.Build()
	File_v1_rpc_parquet_proto = out.File
	file_v1_rpc_parquet_proto_rawDesc = nil
	file_v1_rpc_parquet_proto_goTypes = nil
	file_v1_rpc_parquet_proto_depIdxs = nil
}
