name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Server
      run: go build -o build/douglasie -v ./v1/main.go


    - name: Build CLI
      run: go build -o build/douglasie-cli -v ./v1/cli/main.go

    - name: Upload artifacts server
      uses: actions/upload-artifact@v2
      with:
        name: douglasie
        path: build/douglasie

    - name: Upload artifacts CLI
      uses: actions/upload-artifact@v2
      with:
        name: douglasie-cli
        path: build/douglasie-cli